#ifndef _STLP_INTERNAL_MEMSTAT_H
#define _STLP_INTERNAL_MEMSTAT_H

#ifndef MEMSTAT_REGISTER_CONTAINER
#define MEMSTAT_REGISTER_CONTAINER(...)
#endif

#ifndef MEMSTAT_BIND_TO_CONTAINER
#define MEMSTAT_BIND_TO_CONTAINER(...)
#endif

#ifndef MEMSTAT_USAGE
#define MEMSTAT_USAGE(...)
#endif

#ifndef MEMSTAT_UNREGISTER_CONTAINER
#define MEMSTAT_UNREGISTER_CONTAINER(...)
#endif

#ifndef MEMSTAT_REBIND_TO_CONTAINER
#define MEMSTAT_REBIND_TO_CONTAINER(...)
#endif

#ifndef MEMSTAT_SWAP_CONTAINERS
#define MEMSTAT_SWAP_CONTAINERS(...)
#endif

#endif

