#include "CryHalf.inl"

//#if defined(FP16_MESH)

STRUCT_INFO_BEGIN(CryHalf2)
	STRUCT_VAR_INFO(x, TYPE_INFO(CryHalf))
	STRUCT_VAR_INFO(y, TYPE_INFO(CryHalf))
STRUCT_INFO_END(CryHalf4)

STRUCT_INFO_BEGIN(CryHalf4)
	STRUCT_VAR_INFO(x, TYPE_INFO(CryHalf))
	STRUCT_VAR_INFO(y, TYPE_INFO(CryHalf))
	STRUCT_VAR_INFO(z, TYPE_INFO(CryHalf))
	STRUCT_VAR_INFO(w, TYPE_INFO(CryHalf))
STRUCT_INFO_END(CryHalf4)

//#endif
