#include "Cry_Color.h"

STRUCT_INFO_T_BEGIN(Color_tpl, class, T)
	STRUCT_VAR_INFO(r, TYPE_INFO(T))
	STRUCT_VAR_INFO(g, TYPE_INFO(T))
	STRUCT_VAR_INFO(b, TYPE_INFO(T))
	STRUCT_VAR_INFO(a, TYPE_INFO(T))
STRUCT_INFO_T_END(Color_tpl, class, T)

